services:
  api:
    image: node:20-alpine
    working_dir: /app
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
